### ISSUE TITLE
The recent clinet_side_graphs questions

### ISSUE THREAD

**Issue by Infiltra** [krakenrf/krakensdr_doa#1]
From what I see in client_side_graphs the major update is in the squelch and graphing (addition of waterfall) right?

**Comment by krakenrf** [comment]
Yep currently it adds the waterfall and changes the dash to dash-devices to make the graphs close to real time updates. Normal dash only supports about a 1s refresh rate so pulsed signals would be missed on the graphs.

It also changes the squelch method from time domain to frequency domain via overlapping welch. Time resolution is reduced a bit, but for most use cases it's fine, and the freq domain gives us significantly better squelch resolution.

As the main dev who managed the merges is currently on holiday, i'm also adding CPU performance improvements to this branch. Some algorithms have been optimized, and numba is now used to improve computation speed on the DSP. 

Also added a simpler way to set the DAQ side settings.

Will be writing up a tutorial, install instructions and hopefully an image soon once this branch is stabilized and fully tested.
