### ISSUE TITLE
Add ability to download log files from UI

### ISSUE THREAD

**Issue by krakenrf** [krakenrf/krakensdr_doa#101]
Note for future work. Will be useful for customer debugging.

**Comment by godsic** [comment]
@krakenrf Shell we just put them in `_share`?

**Comment by krakenrf** [comment]
Maybe just a symlink to them will work in _share?

**Comment by godsic** [comment]
@krakenrf Links to shared folders are considered to be bad security practices. Maybe we can create a log sub folder inside _share and write there directly?

**Comment by krakenrf** [comment]
Hm but we also need to be able to get the logs out from the heimdall Firmware/_logs folder, and I don't think it's a good idea to make heimdall write it's logs to the krakensdr_doa/_share folder, since heimdall can be run standalone without krakensdr_doa. 

Perhaps there needs to be a script that periodically copies the logs over. But security wise, what's the difference between a symlink to the logs in another folder, vs copying/writing them directly?

**Comment by krakenrf** [comment]
Also just noting if we're thinking about security, the way Local Data Recording is downloaded will need looking at too, since it's possible to traverse the directory structure via the filename and download anything. Probably just got to sanitize ../
