### ISSUE TITLE
Incorrect output in doa_value.html when selecting DF Aggregator.

### ISSUE THREAD

**Issue by IIvanIvanovich** [krakenrf/krakensdr_doa#136]
I am testing the current software version 1.8. I found the next problem. Incorrect output in doa_value.html when selecting DF Aggregator. This output is similar to kraken, it is not XML. If you select Kerberos, the output format changes to the old short output. So only XML output does not work. Please correct it.

**Comment by krakenrf** [comment]
In the recent updates the DF-Aggragotor output is now doa.xml. You can set DF-Aggregator to use this output now.
