### ISSUE TITLE
Glitch in DoA graph when `Squelch` is active

### ISSUE THREAD

**Issue by godsic** [krakenrf/krakensdr_doa#20]
When DoA estimation is skipped due to the `Squelch` threshold, the DoA graph in web interface gets a few bogus data points around 0 deg with 0 dB amplitude, as shown in the screenshot. Also the DoA angle is reset to 0 instead of holding the last known value.

![image](https://user-images.githubusercontent.com/2339291/177408920-656b53f1-186c-4796-9053-069958f31d83.png)

**Comment by ckoval7** [comment]
I've noticed this issue as well

**Comment by godsic** [comment]
@ckoval7 Made pull request that fixes the issue
