### ISSUE TITLE
Feature Request: Peak Hold in Spectrum Display

### ISSUE THREAD

**Issue by ckoval7** [krakenrf/krakensdr_doa#23]
As the title states, this is a feature request. It would be useful to have a peak hold function in the spectrum display.

**Comment by godsic** [comment]
@ckoval7 Just for visualization or DoA processing as well?

**Comment by ckoval7** [comment]
Just for visualization. It would be nice to have some level persistence in the data too, but that's a different topic.

**Comment by krakenrf** [comment]
Added in https://github.com/krakenrf/krakensdr_doa/commit/98610bc2cb288885e782579418b0524885a58e6e
