### ISSUE TITLE
Provide way to contact KrakenRF team

### ISSUE THREAD

**Issue by cwawak** [krakenrf/krakensdr_doa#28]
Hello, there is no way to contact the KrakenRF team. 

UPS lost my package, and I need someone to file a dispute with UPS on my behalf. I can't file for a refund because so much time went past between ordering and shipping.

Please provide some sort of contact information so that customers that need help can actually get it.

**Comment by krakenrf** [comment]
Hi, first sorry to hear about the UPS issue. If yours shipped from Crowd Supply, then you'll need to contact their support about any shipping issues as they are the ones who shipped it. They will definitely be able to help you. We actually don't have any information or control over the shipping process. Worst case, if Crowd Supply support won't help, you can email us at thekraken@krakenrf.com and we'll poke Crowd Supply to help.

Our website will be ready soon and when we have excess stock over what Crowd Supply backers and Mouser ordered, then we'll start selling some ourselves.
