### ISSUE TITLE
Add clean shutdown button

### ISSUE THREAD

**Issue by krakenrf** [krakenrf/krakensdr_doa#30]
While unlikely, pulling power to the Pi 4 could end up corrupting the SD card.

We should add a shutdown and restart button to the web GUI.

**Comment by formtapez** [comment]
> While unlikely, pulling power to the Pi 4 could end up corrupting the SD card.
> 
> We should add a shutdown and restart button to the web GUI.

Please do so.
I don't want to do it to poor pi to just pull the plug...

**Comment by krakenrf** [comment]
Added in https://github.com/krakenrf/krakensdr_doa/commit/0dfeb1ef8b8a5b2eeb86aab429bbcd9b89107a0e
