### ISSUE TITLE
balenaEtcher-1.5.115 fail to flash microSD

### ISSUE THREAD

**Issue by glenndk** [krakenrf/krakensdr_doa#31]
In the printed KrakenSDR Users Manual on page 11 it is recommended to use balenaEtcher to flash an KrakenSDR DF image. It failed for me. BalenaEtcher (used balenaEtcher-1.5.115.dmg from https://www.balena.io/etcher/ ) could not unmount the SD-card Sandisk Edge 128GB.

My OS is an updated MacOS 10.15.7. I used an elder Trancend SD/MMC adapter, that support up to SDHC - the SD-card is a microSDXC.

A friend recommended to use Raspberry Pi Imager (used imager_1.7.2.dmg found here https://www.raspberrypi.com/software/ ). Raspberry Pi Imager worked (no cog settings was used).

Please consider updating or supplementing your (printed) KrakenSDR Users Manual with the alternative Raspberry Pi Imager.

**Comment by krakenrf** [comment]
Thanks. Weird problem with Etcher though. I've updated on the online Wiki to include an alternative.

The trouble with the printed is that it's not easy to update.
