### ISSUE TITLE
Map server feature request: Multiple receivers, Indicate which bearing is which receiver

### ISSUE THREAD

**Issue by n8rdf** [krakenrf/krakensdr_doa#44]
When using multiple receivers, it's not clear which map bearing is for which receiver. Especially important for mobile Dfing. Suggest adding a bearing source label or some method to correlate receivers with map bearings display.

**Comment by Tysonpower** [comment]
are you talking about the bearing lines or what exactly do you want a label for? Maybe a screenshot would be helpful :)

**Comment by n8rdf** [comment]
![image](https://user-images.githubusercontent.com/17055508/200290742-24033710-0a61-41f5-bc9b-e319d9745288.png)
You have a list of receivers and multiple bearings displayed but can't see which bearing is from which receiver unless you click on one. That might be ok for fixed stations but for mobile(s) it would be nice to have the station name on the map somewhere near the bearing line.

**Comment by Tysonpower** [comment]
Thx for the clearification, added to the TODO list :)

**Comment by n8rdf** [comment]
Datapoint Info popup could/should have receiver ID. (Also, the red hexagons are so small I didn't know they existed until today since I never zoomed in close enough to see them.)
![no receiver ID](https://user-images.githubusercontent.com/17055508/204899410-bd649241-9e4e-4c06-862f-60a27bf11173.jpg)

**Comment by n8rdf** [comment]
Any update on this? I'm trying to put both krakensdr on line and the mapper is confusing to read. Thanks.
![image](https://user-images.githubusercontent.com/17055508/232313003-786e1ed6-30bb-4c26-992f-2ef93b8c8081.png)

**Comment by Tysonpower** [comment]
working on it

**Comment by Tysonpower** [comment]
The stations should be marked with a marker and Name on the Map now with the latest update.
