### ISSUE TITLE
DOA feature request: Display software version

### ISSUE THREAD

**Issue by n8rdf** [krakenrf/krakensdr_doa#45]
Handling multiple Rpi SD cards makes it easy to mix them up. It would be nice if the software/image version could be displayed on the Config screen.

**Comment by n8rdf** [comment]
Regarding Closed Issue #39, the Spectrum tab was updated to correctly show Ch1 as the source, but the DOA Estimation tab still indicates CH0 (should also be CH1?) Minor issue.

**Comment by krakenrf** [comment]
Version now shown inside the system configuration box.
