### ISSUE TITLE
DOA feature request: Display squelch setting on spectrum graph

### ISSUE THREAD

**Issue by n8rdf** [krakenrf/krakensdr_doa#47]
It would help ensure the squelch level was set correctly if a line showing the level was drawn across the spectrum graph. This is especially important for tracking intermittent signals so you're not processing noise or missing transmissions.

**Comment by krakenrf** [comment]
This already exists, a line and shading is drawn across and under the specified threshold. e.g. here the squelch threshold was set to -50 
![image](https://user-images.githubusercontent.com/78108016/200443180-7765be97-ccde-4c2a-9e91-ed2139d39bd8.png)
