### ISSUE TITLE
Feature request: Continue DOA estimates when mobile station stops moving

### ISSUE THREAD

**Issue by n8rdf** [krakenrf/krakensdr_doa#48]
I understand GPS headings go invalid near zero speed. But hearing a very intermittent signal go active when you're stopped at a traffic light or briefly parked and not getting a bearing is frustrating 😭. It seems if you had an auto Stationary on/off mode that would use the last valid gps info when stopped, then go back to live gps when moving again, it would help greatly with intermittent signals. Preferably in the DOA code but minimally in the android app.

**Comment by krakenrf** [comment]
The main DOA code on the PI is constantly spitting out data, even when not moving. It's the Android app that blocks data when not moving.

But there is already a simple setting for that. In the Android app settings just turn off "Pause Data Collection When Stationary". Android should keep the heading stable on most devices, but for some reason some certain devices have the heading go crazy when stopped.
