### ISSUE TITLE
Pi4 Shutdown feature?

### ISSUE THREAD

**Issue by Kingpin348** [krakenrf/krakensdr_doa#50]
Is there any way to safely shut down the Raspberry Pi? With this operating in a headless mode, the only way I have been able to power it off was to just remove power from the Pi. Certainly, this is not good for the SD card or file system. Can a power down option be added where we can press a button in the app to power down the pi, or allow us to use a switch on pins 5&6 to power it down safely?

Thanks, 

JB

**Comment by krakenrf** [comment]
This was added just a few days ago, so please update to the latest image. It's hidden under the "System Control" checkbox to prevent accidental presses.

That said the code doesn't really do any writes to the card during operation, so yanking the power has never resulted in a corruption in all my time using the previous code. But certainly please use the shutdown feature if you can.
