### ISSUE TITLE
DOA Issue: GPS location "Disabled" at startup (Image v1.4)

### ISSUE THREAD

**Issue by n8rdf** [krakenrf/krakensdr_doa#53]
I have the Station Information, Location Source: GPS in my saved config file. At bootup, the system starts operating OK but with the GPS = Disabled status.  I have edited /etc/default/gpsd as 
# Default settings for gpsd.
START_DAEMON="true"
GPSD_OPTIONS="-G"
DEVICES="/dev/gps0"
USBAUTO="true"
GPSD_SOCKET="/var/run/gpsd.sock"
and confirmed the gpsd Daemon is running at startup. 
However, DOA appears to be using the last (possibly invalid) GPS location for DOA reports, both locally and on the Kraken RF map site.
 Deseleting and reselecting GPS as the Location Source appears to allow the GPS to Connect. However, I'm trying to configure a remote DF station that can operate from bootup without user intervention.

**Comment by krakenrf** [comment]
What model GPS puck are you using?

**Comment by n8rdf** [comment]
![image](https://user-images.githubusercontent.com/17055508/205044656-3539e2bc-1e72-408f-9810-6b4f6730f5d7.jpeg)
Ublox 7 and g-mouse ipx6

**Comment by krakenrf** [comment]
Ah is this on the Pi4 image, or a custom setup?

**Comment by n8rdf** [comment]
Pi4 image 1.4

**Comment by krakenrf** [comment]
Fixed in https://github.com/krakenrf/krakensdr_doa/commit/f1ac9e469be9b7df8c09ab20914952bfc497ec80, will be updating the Pi image within the next few days.
