### ISSUE TITLE
Radar Detector?

### ISSUE THREAD

**Issue by gisforgirard** [krakenrf/krakensdr_doa#54]
I've been thinking about it lately, and it seems to me that possibly with some kind of LNB or BDC, it would be possible to use SDR to detect, for example, X/K/Ka-Band radar signals often used for determining vehicle speed.

Current high-end commercial radar detectors cost upwards of $600-800 and often come with two antennas, which is better than only one, but it would seem the almost ideal candidate for this application would be with something like the KrakenSDR.

The main issue would seem to be the fact that these signals are pretty far outside of the typical range of nearly all SDRs and therefore necessitate at the very least some kind of downconverter, but I've been unable to find much (any) information anywhere online about this being performed in practice.

Is coherency being maintained whilst utilizing a downconverter even something that is theoretically possible? I know that the results using similar yet different individual LNA's looked quite positive at least, so it's not really so much of an issue but just a question as to the feasibility of doing something like this in general, so this can be closed if it's the wrong place for something like this...

**Comment by krakenrf** [comment]
Each channel of the downconverter has to share a common clock for coherency to be mainainted.

But for just detecting a radar signal with an LNB, there is no need for coherency. Simply detecting power in that band should be enough.
