### ISSUE TITLE
Kraken Pro Cloud Mapper : how to add another KrakenSDR ?

### ISSUE THREAD

**Issue by HB9IBI** [krakenrf/krakensdr_doa#55]
Hello all,

I've added the first KrakenSDR on my map.krakenrf.com new account and copied the app key, it's working well.

Now i'm trying to add another one, entering the second Kraken serial, name with space, frequency and decay time, clicking on "create station", I received an error . " error : you forgot to fill all fields or entered a wrong serial"

What's wrong ?

Regards and happy doa ;) !

François

**Comment by krakenrf** [comment]
If it's still not working please email thekraken@krakenrf.com with your serial number. It's possible that some newer serials were not added to the system, so it wasn't recognizing them.
