### ISSUE TITLE
Error 404 when accessing PHP Data Out Server Running at 0.0.0.0:8081

### ISSUE THREAD

**Issue by eugenegorelikov** [krakenrf/krakensdr_doa#58]
Title describes the issue. Whenever I am getting solid 404 whenever I'm trying to run the DOA on my Ubuntu (used the official install script). The same happens on Raspberry Pi with official image. 0.0.0.0:8080 on the local machine or [raspberry_pi_ip]:8080 is resolving fine

**Comment by krakenrf** [comment]
You need to access http://PI4_IP_ADDR:8081/DOA_value.html. The root is not defined.
