### ISSUE TITLE
Conversion to JSON

### ISSUE THREAD

**Issue by ckoval7** [krakenrf/krakensdr_doa#8]
https://github.com/krakenrf/krakensdr_doa/blob/91842c181b2d3b6c27f9f8d3f4bfa690c8723ab6/_signal_processing/krakenSDR_signal_processor.py#L300

What is the timeline for converting from CSV to JSON? If it's a long way out, would you be open to a pull request adding lat, lon and heading in place of a few of the reserved values? What's the correct branch to be using at the moment?

**Comment by krakenrf** [comment]
Please check the main branch and see if this feature still works. I made some larger changes and just manually moved this code into the latest branch. It should be working fine. I've also specified the outputs by application name, rather than data output type.
